### ISSUE TITLE
Add contributor

### ISSUE THREAD

**Issue by nwlandry** [pszufe/HIF_validators#1]
@pszufe, do you mind adding me to the list of contributors?

**Comment by colltoaction** [comment]
As a sidenote I'm not a NetworkX maintainer

**Comment by pszufe** [comment]
@nwlandry I added you - sorry for omitting that!. Note that you have full access to the repository so feel free to update the README if you see anything missing.

**Comment by pszufe** [comment]
@colltoaction , I updated that header - does it make more sense now? Or you can just update it too :) I understand that we aim to some networkx compatibility?

**Comment by colltoaction** [comment]
Exactly :)

**Comment by nwlandry** [comment]
@pszufe thanks! I think this issue is now addressed.
